name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - geopandas
  - osmnx
  - momepy
  - plotly
  - Rtree
  - geocoder
  - scikit-learn
  - statsmodels
  - h3pandas
  - streamlit
